# Google Analytics Tracking ID
google_analytics:

# Default portfolio post
default_cover_image: images/unsplash.jpg
default_post_title: Portfolio Item

# Header
menu:
About: /aboutagram.com
Sources: /source
LinkedIn: https://www.linkedin.co
Contact: /contact
Instagram: https://www.instm
Facebook: https://www.facebook.com